#!/bin/bash
#exec w3m "duckduckgo.com/lite?kd=-1&kp=-1&q=$*"


useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/601.1.15 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Lynx"

function dock {
	url="https://lite.duckduckgo.com/lite?kd=-1&kp=-1&q=$(urlencode "$*")" # 🦆
	#chat "🦆 searching: $* $url"
	lynx "-prettysrc=glow --useragent=$useragent" "${url}"
	#exec w3m "$url"
} && export -f dock

function google {
	url="https://google.com/search?q=$(urlencode "$*")"
	#chat "$url"
	# exec lynx "https://google.com/search?q=$url"
	#useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.79 Safari/537.1"
	lynx "--useragent=$useragent" "${url}"
} && export -f google

function wiki {
  url="https://en.wikipedia.org/wiki/Special:Search/$(urlencode "$*")"
  lynx "${url}"
} && export -f wiki

function ml {
  url="https://machinelearningmastery.com/?s=$(urlencode "$*")&post_type=post&submit=Search"
  lynx "${url}"
} && export -f ml

function meaning {
  url="https://www.merriam-webster.com/dictionary/$(urlencode "$*")"
  lynx "${url}"
} && export -f meaning

function gtr {
  sl='auto'
  tl=$1
  shift
  base_url="https://translate.googleapis.com/translate_a/single?client=gtx&sl=${sl}&tl=${tl}&dt=t&q="
  qry=$( echo $@ | sed -e "s/\ /+/g" )
  full_url=${base_url}${qry}
  response=$(curl -sA "${useragent}" "${full_url}")
  echo ${response}  | sed 's/","/\n/g' | sed -E 's/\[|\]|"//g' | head -1
}


