#!/usr/bin/bash

[[ -z $SNPPETS ]] && echo "SNIPPETS	 directory undefined" && exit 1

echo "$SNIPPETS"
# declare -a COMMANDS=(foo bar blah)
# complete -F kirubel kirubel
if [[ -n $COMP_LINE ]]; then
	printf "foo\nbar\nblah"
	echo "test"
	#for cmd in ${COMMANDS[@]}; do
	#done
	exit
fi

