prSections:
  - title: Mine
    filters: is:open author:@me
    layout:
      author:
        hidden: true
    type: null
  - title: Review
    filters: is:open review-requested:@me
    limit: 10
    type: null
  - title: Involved
    filters: is:open involves:@me -author:@me
    type: null
  - title: All
    filters: repo:bbgithub.dev.bloomberg.com/BQL/
    type: null
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit
  issues: []
  prs:
    - key: C
      command: >
        tmux split-window -h -c {{.RepoPath}}
        "nvim -c 'Octo pr edit {{.PrNumber}}' || read -p 'Press Enter o closse... '"
  branches: []
repoPaths:
  BQL/*: ~/dev/*,
  kirubeltadesse/dotfiles: ~/.dotfiles,
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: delta
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
