prSections:
  - title: Mine
    filters: is:open author:@me
    layout:
      author:
        hidden: true
    type: null
  - title: Review
    filters: is:open involves:@me involves:iakilov -author:app/renovatebot involves:ikeddie involves:@sdige -author:@me sort:updated-desc
    limit: 10
    type: null
  - title: Hits
    filters: is:open interactions:5..10 -author:iakilov -author:app/renovatebot -author:ikeddie -author:@sdige -author:@me org:BQL sort:updated-desc
    limit: 10
    type: null
  - title: Hits
    filters: is:open interactions:5..10 -author:@voswal1 -author:@sdige -author:@me org:BQL sort:updated-desc
    limit: 10
    type: null
  - title: Merged
    filters: is:closed involves:@me
    type: null
  - title: All
    filters: involves:@me involves:iakilov involves:ikeddie involves:@sdige sort:updated-desc
    type: null
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Subscribed
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true

  preview:
    open: true
    width: 84
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
repoPaths: {
  BQL/*: ~/dev/*,
  kirubeltadesse/dotfiles: ~/.dotfiles,
  Swarmies/*: ~/projects/*,
  }
keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit
  issues: []
  prs:
    - key: D
      name: debug path
      command: >
        echo 'Repo Path: {{.RepoPath}} Pr Number: {{.PrNumber}} Issue Number: {{.IssueNumber}}'
    - key: C
      command: >
        tmux split-window -h -c {{.RepoPath}}
        "nvim -c ':Octo pr edit {{.PrNumber}}' "
  branches: []
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: delta
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
