#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config auto_balance on
yabai -m config split_ratio 0.5

yabai -m config window_placement second_child
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autoraise

yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

yabai -m config external_bar off:0:0

# Let floating/system apps manage themselves.
yabai -m rule --add app='System Settings' manage=off
yabai -m rule --add app='Calculator' manage=off
yabai -m rule --add app='App Store' manage=off
