#!/bin/bash
# Toggle between U.S. and Geez-QWERTY (Amharic) input methods
IM=/opt/homebrew/bin/im-select
CURRENT=$($IM)

if [ "$CURRENT" = "com.apple.keylayout.US" ]; then
    $IM com.apple.keylayout.Geez-QWERTY
else
    $IM com.apple.keylayout.US
fi
