#!/bin/bash
# Toggle between U.S. and Geez-QWERTY (Amharic) input methods
IM=/etc/profiles/per-user/kirubeltadesse/bin/macism
CURRENT=$($IM)

if [ "$CURRENT" = "com.apple.keylayout.US" ]; then
    $IM com.apple.keylayout.Geez-QWERTY
else
    $IM com.apple.keylayout.US
fi
